apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sproject
  template:
    metadata:
      labels:
        app: k8sproject
    spec:
      containers:
      - name: k8sproject
        image: k8sproject:latest
        ports:
        - containerPort: 8080
